### ISSUE TITLE
Modrinth potion description link is wrong

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Binaris00/Fabric_Potions#1]
On Mondrinth, the link for "here" in
> This mod have 26 effects/potions, so if you want to see al the descriptions and the recipes go here

Leads back to the modrinth page, not the description page on this repo. 

(also it should be)
> This mod **has** 26 effects/potions, so if you want to see **all** the descriptions and the recipes go **here.**

**Comment by Binaris00** [comment]
Solved! Thanks for the help :D

**Comment by supersaiyansubtlety** [comment]
Hm, it still leads back to the Modrinth page...

**Comment by supersaiyansubtlety** [comment]
It's working now
